---
- hosts: 10.166.0.2
  tasks:
  - name: Set authorized key taken from file
    authorized_key:
      user: jenkins
      state: present
      key: "{{ lookup('file', '/home/jjharry444/.ssh/id_rsa.pub') }}"
    become: true
...
