---
- hosts: db_hosts
  become: yes
  tasks:
  - name: Install MariaDB
    package:
      name: mariadb-server
      state: latest
  - name: Start MariaDB
    service:
      name: mariadb
      state: started 
      enabled: yes
  - name: Set MariaDB root password for the first time (root@localhost)
    mysql_user:
      name: root
      password: "password"
#      host: localhost
      state: present
...
        
